widgetTheme=widget-themes/original
primaryColor=#015807
secondaryColor=#7a7676
labelColor=#ffffff
hideWhenOffline=false
contactMail=info@ciertoglobal.org
loadingLabel=Cargando...
loginError=Error
chatHeader=<strong>Chatea con nosotros</strong>
startInfo=Llena los campos
widgetWidth=370
widgetHeight=411
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
messageSound=audio/default.mp3
startLabel=Comenzar
backLabel=Regresar
initMessageBody=Hola, como puedo ayudarte?
initMessageAuthor=Operador
chatInputLabel=Escribe tu pregunta
timeDaysAgo=dias
timeHoursAgo=horad
timeMinutesAgo=minutos
timeSecondsAgo=segundos
offlineMessage=Operador fuera de linea
toggleSoundLabel=Efectos de sonido
toggleScrollLabel=Auto-scroll
toggleEmoticonsLabel=Emoticons
toggleAutoShowLabel=Auto-mostrar
toggleFullscreenLabel=Pantalla completa
endChatLabel=Terminar el chat
endChatConfirmQuestion=Estas seguro?
endChatConfirm=Si
endChatCancel=Cancelar
contactHeader=<strong>CONTÁCTANOS</strong>
contactInfo=Todos nuestros operadores están fuera de linea.<br> Usa el formulario para dejar un mensaje urgente, reportar una emergencia o darnos tu opinión. <br>Cuentas con nosotros.
contactNameLabel=Nombre
contactMailLabel=Correo electrónico
contactQuestionLabel=Tu pregunta
contactSendLabel=Enviar
contactSuccessHeader=Mensaje enviado
contactSuccessMessage=Tu pregunta fué enviada. Gracias!
contactErrorHeader=Error
contactErrorMessage=Hubó un error
headerHeight=55
installed=1
autoShowWidgetAfter=10
autoShowWidget=true
askForMail=true
